platform :ios, '8.0'

target 'FirebaseFirestoreUI' do
  use_frameworks!

  pod 'FirebaseFirestore'

  target 'FirebaseFirestoreUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
